CREATE TABLE `user_profile` (
    id int AUTO_INCREMENT,
    login_app_id INTEGER,
    owner_address VARCHAR (100),
    owner_city VARCHAR (30),
    owner_state VARCHAR (2),
    owner_zip INTEGER,
    dog_name VARCHAR (25),
    dog_age INTEGER (2),
    dog_breed VARCHAR (30),
    dog_gender VARCHAR (6),
    dog_color VARCHAR (30),
    dog_birthdate VARCHAR (5),
    dog_allergies VARCHAR (200),
    dog_weight INTEGER (3),
    dog_friendly BOOLEAN,
    amt_walks INTEGER (2),
    amt_meals INTEGER (2),
    amt_per_meal INTEGER (2),
    dog_potty_trained BOOLEAN,
    dog_fixed BOOLEAN,
    UNIQUE KEY login_id_UNIQUE (login_app_id),
    INDEX (id),
    FOREIGN KEY (login_app_id) REFERENCES login_app(id)
);