CREATE TABLE appointments (
	 appointment_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
     id INT,
     start_time VARCHAR(255) NOT NULL,
	 end_time VARCHAR(255),
	 start_date VARCHAR(255) NOT NULL,
	 end_date VARCHAR(255),	 
     description VARCHAR(255),
	 is_consultation TINYINT,
    is_confirmed TINYINT,
    is_rejected TINYINT,
     first_name VARCHAR(255),
     last_name VARCHAR(255),
     email VARCHAR(255),
     username VARCHAR(255),
    INDEX (id),
    -- INDEX (first_name),
    -- INDEX (last_name),
    -- INDEX (email),
    INDEX (username),
    FOREIGN KEY (id) REFERENCES login_app(id),
    -- FOREIGN KEY (first_name) REFERENCES login_app(first_name),
    -- FOREIGN KEY (last_name) REFERENCES login_app(last_name),
    -- FOREIGN KEY (email) REFERENCES login_app(email),
    FOREIGN KEY (username) REFERENCES login_app(username)
);