CREATE TABLE user_profile (
    FOREIGN KEY (id) REFERENCES login_app(id),
    FOREIGN KEY (first_name) REFERENCES login_app(first_name),
    FOREIGN KEY (last_name) REFERENCES login_app(last_name),
    FOREIGN KEY (email) REFERENCES login_app(email),
    FOREIGN KEY (username) REFERENCES login_app(username),
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    ownerAddress VARCHAR (100),
    ownerCity VARCHAR (30),
    ownerState VARCHAR (2),
    ownerZip INTEGER,
    ownerEmail VARCHAR (50),
    dogName VARCHAR (25),
    dogBreed VARCHAR (30),
    dogGender VARCHAR (6),
    dogColor VARCHAR (30),
    dogBirthdate VARCHAR (5),
    dogAllergies VARCHAR (200),
    dogWeight INTEGER (3),
    dogFriendly BOOLEAN,
    amtWalks INTEGER (2),
    amtMeals INTEGER (2),
    dogPottyTrained BOOLEAN,
    dogFixed BOOLEAN
);